import { LineEdit } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { Divider } from "../base/divider.slint";

export component Header inherits Rectangle {
    property<length> label-width: 100px;
    height: Theme.header-height;

    HorizontalLayout {
        alignment: space-between;

        HorizontalLayout {
            spacing: Theme.spacing;
            padding: Theme.padding / 2;
            padding-left: Theme.padding;
            property<bool> is-edit: false;

            Text {
                vertical-alignment: center;
                text: Store.translator.net-label;
                font-size: Theme.default-font-size - 4px;
            }

            if !is-edit : Rectangle {
                width: root.label-width;
                VerticalLayout {
                    alignment: center;
                    padding-left: Theme.padding;
                    padding-right: Theme.padding;

                    Text {
                        text: Store.user-name;
                        font-size: Theme.default-font-size - 4px;
                        overflow: elide;
                    }
                }
                ta := TouchArea {
                    mouse-cursor: self.has-hover ? pointer : default;
                    clicked => {
                        is-edit = !is-edit;
                    }
                }
            }

            if is-edit : LineEdit {
                width: root.label-width;
                text: Store.user-name;
                font-size: Theme.default-font-size - 4px;
                accepted => {
                    Logic.set-user-name(self.text);
                    is-edit = !is-edit;
                }
            }

        }

        HorizontalLayout {
            VerticalLayout {
                alignment: center;
                HorizontalLayout {
                    IconBtn {
                        icon: @image-url("../images/reset.svg");
                        icon-width: Theme.icon-size * 0.7;
                        tip-pos: "left";
                        tip-text: Store.translator.tip-flush-session;
                        clicked => {
                            Logic.flush-sessions();
                        }
                    }
                }
            }

            VerticalLayout {
                alignment: center;
                padding-left: Theme.padding * 2;
                padding-right: Theme.padding * 2;

                Divider {
                    width: 2px;
                    height: root.height * 0.5;
                    background: Theme.base-border-color;
                }
            }

            VerticalLayout {
                alignment: center;
                HorizontalLayout {
                    spacing: Theme.spacing * 2;
                    IconBtn {
                        icon: @image-url("../images/setting-fill.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-setting;
                        clicked => {
                            Store.setting-dialog-config.show = true;
                        }
                    }

                    IconBtn {
                        icon: @image-url("../images/help.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-help;
                        clicked => {
                            Store.help-dialog.show = true;
                        }
                    }

                    IconBtn {
                        icon: @image-url("../images/info-dark.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-about;
                        clicked => {
                            Store.about-dialog.show = true;
                        }
                    }
                }
            }
        }
    }
}
