import { Theme } from "../theme.slint";
import { Logic } from "../logic.slint";
import { Store } from "../store.slint";
import { Body } from "./body/panel.slint";
import { Footer } from "./footer.slint";
import { Divider } from "../base/divider.slint";

export component RPanel inherits VerticalLayout {
    in-out property question <=> footer.question;
    in-out property chats-viewport-y <=> body.viewport-y;
    forward-focus: footer;

    body := Body { }
    footer := Footer { }
}

