import { Translator, Translation} from "./translator.slint";
import { MDItem } from "./base/data.slint";

export struct ChatItem {
    type: string,
    text: string,
    timestamp: string,
}

export struct ChatSession {
    uuid: string,
    name: string,
    avatar: image,
    status: string,
    chat-items: [ChatItem]
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct OkCancelDialogSetting {
    title-type: string,
    title-text: string,
    body-text: string,
    handle-type: string,
    handle-uuid: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    win-width: string,
    win-height: string,
    language: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export global Store  {
    in-out property<[ChatItem]> session-datas: [
        // {
        //     type: "uitem",
        //     text: "hello world ejfiwejfwij fwij wijfweifj wiofjw iofjwiofjwe iojfwioj fwjeifjwei ffwiofj wiejf wiofjw ijfwie wejfiwej fiwfjweif jwiefjwif jweif\n wjfiwej iwjwfie ",
        //     timestamp: "2023-12-03 12:03:45",
        // },
        // {
        //     type: "bitem",
        //     text: "int main()\n{\n    printf('hello world');\n}",
        //     timestamp: "2023-12-03 12:03:45",
        // },
        // {
        //     type: "uitem",
        //     text: "基金法飞机无法及附加",
        //     timestamp: "2023-12-03 12:03:45",
        // }
    ];

    in-out property<[ChatSession]> chat-sessions: [
        // {
        //     name: "会话1",
        //     uuid: "default-session-xxxuuid",
        // },
        // {
        //     name: "会话2",
        //     uuid: "default-session-xxuuid",
        // },
    ];

    in-out property<string> user-name: "gossip name";
    in-out property<string> current-session-uuid;
    in-out property<MessageItem> message;
    in-out property<OkCancelDialogSetting> ok-cancel-dialog-setting;

    in-out property<SettingDialogConfig> setting-dialog-config: {
        show: false,
        ui: {
            font-size: "18",
            font-family: "SourceHanSerifCN",
            win-width: "1200",
            win-height: "600",
            language: "cn",
        }
    };

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "gossipbox v1.0.0",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
              "配置和数据:\n"
            + "  1. 配置保存在~/.config/chatbox目录下。\n"
            + "  2. 数据保存在~/.local/share/chatbox目录下。\n"
            + "\n注意事项:\n"
            + "  1. 删除会话会将该会话关联的归档文件一并删除。\n"
            + "\n快捷键:\n"
            + "  1. Ctrl+[: 当前会话滚动到顶部。\n"
            + "  2. Ctrl+]: 当前会话滚动到底部。\n"
            + "  3. Ctrl+U: 切换最近两个会话。\n"
            + "  9. Ctrl+G: 重置当前会话。\n"
            + " 13. Ctrl+M: 重新提问最后一个问题。\n"
            + " 14. Ctrl+I: 定位到提问框。\n"
            + " 17. Ctrl+J: 会话向下滚动25%。\n"
            + " 18. Ctrl+K: 会话向上滚动25%。\n",

        text-en:
              "Configuration And Data:\n"
            + "  1. Configuration is stored in the ~/.config/chatbox directory.\n"
            + "  2. Data is stored in the ~/.local/share/chatbox directory.\n"
            + "\nNotice:\n"
            + "  1. Deleting a session will also delete the associated archive file.\n"
            + "\nKeyboard Shortcuts:\n"
            + "  1. Ctrl+[: Scroll to the top of the current session.\n"
            + "  2. Ctrl+]: Scroll to the bottom of the current session.\n"
            + "  3. Ctrl+U: Switch between the last two sessions.\n"
            + "  9. Ctrl+G: Reset Current Session.\n"
            + " 13. Ctrl+M: Retry the last question.\n"
            + " 14. Ctrl+I: Focus on question input box.\n"
            + " 17. Ctrl+J: Scroll down the conversation by 25%.\n"
            + " 18. Ctrl+K: Scroll up the conversation by 25%.\n",
    };

    in-out property<Translation> translator: Translator.translation(setting-dialog-config.ui.language == "cn");
}
